# Generated by Django 3.1.2 on 2020-12-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='bin_data',
            field=models.BinaryField(default=b'Vdovichenko Huipliot'),
        ),
    ]
